-- =========================================================
-- SEED: Master Data Downtime (Problem Kategori, Problem Detail, Area)
-- Berlaku sama untuk semua 6 line Welding (E-02..E-07).
-- Jalankan SETELAH migration_downtime_format_v3.sql
-- Aman dijalankan berulang (on conflict -> update/skip).
-- =========================================================

-- 1) Problem Kategori (54 kategori x 6 line = 324 baris)
insert into public.downtime_problems (mesin, value, pic)
select m.mesin, t.value, t.pic
from (values
  ('E-02'::machine_type), ('E-03'::machine_type), ('E-04'::machine_type), ('E-05'::machine_type), ('E-06'::machine_type), ('E-07'::machine_type)
) as m(mesin)
cross join (values
  ('O Bending Oval', 'DIES'),
  ('Hasil Tig Welding bolong', 'PE'),
  ('Tab Cut Burry', 'DIES'),
  ('Hasil Spining pecah', 'PE'),
  ('Akurasi Case spining NG (Panjang Pendek Spining NG)', 'PE'),
  ('Mat keluar dari Catalyst', 'PE'),
  ('Kamera Alarm', 'PE'),
  ('Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)', 'PE'),
  ('Welding bolong', 'PE'),
  ('Part di Leak Test bocor', 'PE'),
  ('Pressure Leak Test tidak tercapai', 'PE'),
  ('Leak Test bocor', 'PE'),
  ('Akurasi Bracket NG', 'PE'),
  ('Akurasi Pipa NG', 'PE'),
  ('Akurasi Flatness NG', 'PE'),
  ('Akurasi Boss/Hole FLange/EGR NG', 'PE'),
  ('Stamp Marking Unclear', 'PE'),
  ('Spater di part', 'PE'),
  ('Bracket Abnormal', 'PE'),
  ('Datum Pin Abnormal', 'PE'),
  ('Clamper Abnormal (Clamp kendor, Clamp aus, Clamp rusak)', 'PE'),
  ('Cover Jig Abnormal (Cover rusak, Baut Cover patah/hilang)', 'PE'),
  ('Hammering Abnormal', 'PE'),
  ('Clamp Unclamp Cylinder Fault', 'MESIN'),
  ('Workset no Detect', 'MESIN'),
  ('Kabel short circuit', 'MESIN'),
  ('Keropos pada weldingan', 'MESIN'),
  ('Servo motor axis Error', 'MESIN'),
  ('Encoder Batterai Fault', 'MESIN'),
  ('Short circuit pada robot', 'MESIN'),
  ('Push button rusak', 'MESIN'),
  ('Pendant Robot rusak', 'MESIN'),
  ('Lack of Phase', 'MESIN'),
  ('Alarm Light curtain error', 'MESIN'),
  ('Pressure leak test error', 'MESIN'),
  ('Wire Stick', 'MESIN'),
  ('Alarm motion Fault', 'MESIN'),
  ('Training', 'PROD'),
  ('Sosialisasi', 'PROD'),
  ('Genba', 'PROD'),
  ('Wire habis', 'PROD'),
  ('Wire Macet', 'PROD'),
  ('Baut kendor', 'PROD'),
  ('Karet Leaktest', 'PROD'),
  ('Tirai error', 'PROD'),
  ('Angin bocor', 'PROD'),
  ('Part pending', 'PROD'),
  ('Reset', 'PROD'),
  ('Material', 'PROD'),
  ('Supplay Telat', 'PC-SUPP'),
  ('Akurasi part', 'QC'),
  ('Part Dakon', 'PRESS'),
  ('Anti Rust Berlebih', 'PRESS'),
  ('Part Jumping Proses', 'PRESS')
) as t(value, pic)
on conflict (mesin, value) do update set pic = excluded.pic;

-- 2) Problem Detail (213 pasangan kategori+detail x 6 line = 1278 baris)
insert into public.downtime_causes (mesin, value, problem_kategori)
select m.mesin, t.value, t.kategori
from (values
  ('E-02'::machine_type), ('E-03'::machine_type), ('E-04'::machine_type), ('E-05'::machine_type), ('E-06'::machine_type), ('E-07'::machine_type)
) as m(mesin)
cross join (values
  ('Part Dakon', 'Part Dakon'),
  ('Anti Rust Berlebih', 'Anti Rust Berlebih'),
  ('Part Jumping Proses', 'Part Jumping Proses'),
  ('tig welding bolong', 'Hasil Tig Welding bolong'),
  ('Tourch Geser', 'Hasil Tig Welding bolong'),
  ('Clamp Longgar', 'Hasil Tig Welding bolong'),
  ('Welding Over', 'Hasil Tig Welding bolong'),
  ('Parameter Tidak Std', 'Hasil Tig Welding bolong'),
  ('spinning crack', 'Hasil Spining pecah'),
  ('Tig Welding Geser', 'Hasil Spining pecah'),
  ('Parameter Kurang', 'Hasil Spining pecah'),
  ('Heater Kurang Panas', 'Hasil Spining pecah'),
  ('converter pendek', 'Akurasi Case spining NG (Panjang Pendek Spining NG)'),
  ('akurasi case spinning ng', 'Akurasi Case spining NG (Panjang Pendek Spining NG)'),
  ('Chuck Aus', 'Akurasi Case spining NG (Panjang Pendek Spining NG)'),
  ('Stopper Pokayoke', 'Akurasi Case spining NG (Panjang Pendek Spining NG)'),
  ('Rumah Chuck Kotor', 'Akurasi Case spining NG (Panjang Pendek Spining NG)'),
  ('roll mat miring', 'Mat keluar dari Catalyst'),
  ('mat keluar dari catalyst', 'Mat keluar dari Catalyst'),
  ('kamera photo alarm', 'Kamera Alarm'),
  ('photo sensor error', 'Kamera Alarm'),
  ('welding tembus', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding meler', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding geser', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding kecil', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding undercut', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding blow hole', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding keriting', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding keropos', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding meleset', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding jendol', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding pin hole', 'Bead Weld NG (Undercut, Blow Hole, Keriting, Bead Kecil, Keropos)'),
  ('welding bolong', 'Welding bolong'),
  ('wire tembus', 'Welding bolong'),
  ('sensor boss bocor', 'Part di Leak Test bocor'),
  ('welding bocor', 'Part di Leak Test bocor'),
  ('jig pipe oblak/ baut slek', 'Pressure Leak Test tidak tercapai'),
  ('pipe leaktest bocor', 'Leak Test bocor'),
  ('flange 1 leaktest bocor', 'Leak Test bocor'),
  ('pin flange 1 lekatest aus', 'Leak Test bocor'),
  ('pin flange 1 lekatest patah', 'Leak Test bocor'),
  ('akurasi ng bkt 1', 'Akurasi Bracket NG'),
  ('akurasi ng bkt 2', 'Akurasi Bracket NG'),
  ('akurasi ng bkt 3', 'Akurasi Bracket NG'),
  ('akurasi ng bkt 4', 'Akurasi Bracket NG'),
  ('akurasi ng bkt 5', 'Akurasi Bracket NG'),
  ('akurasi ng bkt 6', 'Akurasi Bracket NG'),
  ('akurasi pipa ng', 'Akurasi Pipa NG'),
  ('akurasi flatnes ng', 'Akurasi Flatness NG'),
  ('akurasi flange 1 ng', 'Akurasi Boss/Hole FLange/EGR NG'),
  ('akurasi flange 2 ng', 'Akurasi Boss/Hole FLange/EGR NG'),
  ('akurasi bosh mentok', 'Akurasi Boss/Hole FLange/EGR NG'),
  ('stamp marking unclear', 'Stamp Marking Unclear'),
  ('a', 'Spater di part'),
  ('bracket gap', 'Bracket Abnormal'),
  ('bracket miring', 'Bracket Abnormal'),
  ('pin kendor', 'Datum Pin Abnormal'),
  ('pin hilang', 'Datum Pin Abnormal'),
  ('pin rusak', 'Datum Pin Abnormal'),
  ('lock hand clamp rusak', 'Clamper Abnormal (Clamp kendor, Clamp aus, Clamp rusak)'),
  ('clamper rusak', 'Clamper Abnormal (Clamp kendor, Clamp aus, Clamp rusak)'),
  ('cover rusak/ kendor', 'Cover Jig Abnormal (Cover rusak, Baut Cover patah/hilang)'),
  ('cover jig rusak', 'Cover Jig Abnormal (Cover rusak, Baut Cover patah/hilang)'),
  ('cover bracket rusak', 'Cover Jig Abnormal (Cover rusak, Baut Cover patah/hilang)'),
  ('cover pipa rusak', 'Cover Jig Abnormal (Cover rusak, Baut Cover patah/hilang)'),
  ('cover flange rusak', 'Cover Jig Abnormal (Cover rusak, Baut Cover patah/hilang)'),
  ('hammering rusak', 'Hammering Abnormal'),
  ('clamper rusak', 'Hammering Abnormal'),
  ('vibration ng', 'Hammering Abnormal'),
  ('kabel red switch putus', 'Clamp Unclamp Cylinder Fault'),
  ('sensor red switch abnormal', 'Clamp Unclamp Cylinder Fault'),
  ('Selenoid Error', 'Clamp Unclamp Cylinder Fault'),
  ('sensor pokayoke rusak', 'Workset no Detect'),
  ('kabel sensor putus', 'Workset no Detect'),
  ('Red Switch Rusak', 'Workset no Detect'),
  ('Proximity Rusak', 'Workset no Detect'),
  ('Red Switch Geser', 'Workset no Detect'),
  ('kabel metacon putus', 'Kabel short circuit'),
  ('metacon rusak', 'Kabel short circuit'),
  ('breaker trip', 'Kabel short circuit'),
  ('selang gas bocor', 'Keropos pada weldingan'),
  ('solenoid valve rusak', 'Keropos pada weldingan'),
  ('Selang Angin Bocor', 'Keropos pada weldingan'),
  ('Cylinder Bocor', 'Keropos pada weldingan'),
  ('Nipple Bocor', 'Keropos pada weldingan'),
  ('encoder eror', 'Servo motor axis Error'),
  ('servo motor oblak', 'Servo motor axis Error'),
  ('servo amplifier axis error', 'Servo motor axis Error'),
  ('ipm error', 'Servo motor axis Error'),
  ('encoder baterai fault', 'Encoder Batterai Fault'),
  ('alarm robot short circuit', 'Short circuit pada robot'),
  ('torch welding rusak', 'Short circuit pada robot'),
  ('push button rusak', 'Push button rusak'),
  ('kabel push button putus', 'Push button rusak'),
  ('pendant booting', 'Pendant Robot rusak'),
  ('pendant rusak', 'Pendant Robot rusak'),
  ('alarm robot', 'Lack of Phase'),
  ('ligt curtain kotor', 'Alarm Light curtain error'),
  ('light curtain rusak', 'Alarm Light curtain error'),
  ('L/C Tidak Center', 'Alarm Light curtain error'),
  ('presure switch error', 'Pressure leak test error'),
  ('solenoid valve rusak', 'Pressure leak test error'),
  ('sensor red switch error', 'Clamp Unclamp Cylinder Fault'),
  ('solenoid valve rusak', 'Clamp Unclamp Cylinder Fault'),
  ('sensor rusak', 'Alarm motion Fault'),
  ('solenoid valve rusak', 'Alarm motion Fault'),
  ('Training proses retap', 'Training'),
  ('Training proses spinning', 'Training'),
  ('Training proses robot', 'Training'),
  ('Training proses lekatest', 'Training'),
  ('Training proses inspeck', 'Training'),
  ('Accident', 'Sosialisasi'),
  ('Problem', 'Sosialisasi'),
  ('Audit', 'Sosialisasi'),
  ('Rule', 'Sosialisasi'),
  ('WIre tembus', 'Sosialisasi'),
  ('OPL', 'Sosialisasi'),
  ('Qualilty', 'Sosialisasi'),
  ('Customers', 'Genba'),
  ('Management', 'Genba'),
  ('Tamu', 'Genba'),
  ('HSE', 'Genba'),
  ('QA', 'Genba'),
  ('Robot 1', 'Wire habis'),
  ('Robot 2', 'Wire habis'),
  ('Robot 3', 'Wire habis'),
  ('Robot 4', 'Wire habis'),
  ('Robot 5', 'Wire habis'),
  ('Datum Pin Rusak', 'Baut kendor'),
  ('Datum Pin Kendor', 'Baut kendor'),
  ('Datum Pin Aus', 'Baut kendor'),
  ('Hand Clamp Jig 1', 'Baut kendor'),
  ('Hand Clamp Jig 2', 'Baut kendor'),
  ('Hand Clamp Jig 3', 'Baut kendor'),
  ('Hand Clamp Jig 4', 'Baut kendor'),
  ('Hand Clamp Jig 5', 'Baut kendor'),
  ('Hand Clamp Jig 6', 'Baut kendor'),
  ('Hand Clamp Jig 7', 'Baut kendor'),
  ('Hand Clamp Jig 8', 'Baut kendor'),
  ('Cover Jig 1', 'Baut kendor'),
  ('Cover Jig 2', 'Baut kendor'),
  ('Cover Jig 3', 'Baut kendor'),
  ('Cover Jig 4', 'Baut kendor'),
  ('Cover Jig 5', 'Baut kendor'),
  ('Cover Jig 6', 'Baut kendor'),
  ('Cover Jig 7', 'Baut kendor'),
  ('Cover Jig 8', 'Baut kendor'),
  ('Clamper Jig 1', 'Baut kendor'),
  ('Clamper Jig 2', 'Baut kendor'),
  ('Clamper Jig 3', 'Baut kendor'),
  ('Clamper Jig 4', 'Baut kendor'),
  ('Clamper Jig 5', 'Baut kendor'),
  ('Clamper Jig 6', 'Baut kendor'),
  ('Clamper Jig 7', 'Baut kendor'),
  ('Clamper Jig 8', 'Baut kendor'),
  ('Insulator Rusak', 'Baut kendor'),
  ('Red Switch Kendor', 'Baut kendor'),
  ('Red Switch Rusak', 'Baut kendor'),
  ('Grounding Rusak', 'Baut kendor'),
  ('Grounding Aus', 'Baut kendor'),
  ('Grounding Kendor', 'Baut kendor'),
  ('Chuck Rusak', 'Baut kendor'),
  ('Chuck Aus', 'Baut kendor'),
  ('Chuck Kendor', 'Baut kendor'),
  ('Baut Sensor Camera Rusak', 'Baut kendor'),
  ('Baut Sensor Camera Kendor', 'Baut kendor'),
  ('Baut Cylinder Washing Kendor', 'Baut kendor'),
  ('Baut Cylinder Washing Rusak', 'Baut kendor'),
  ('Baut Clamper Washing Rusak', 'Baut kendor'),
  ('Baut Clamper Washing Kendor', 'Baut kendor'),
  ('Spring cover bracket 1', 'Baut kendor'),
  ('Spring cover bracket 5', 'Baut kendor'),
  ('Karet Pipa Rusak', 'Karet Leaktest'),
  ('Karet Flange 1 Rusak', 'Karet Leaktest'),
  ('Karet Sensor Bos Rusak', 'Karet Leaktest'),
  ('Tirai Rusak', 'Tirai error'),
  ('Tirai Macet', 'Tirai error'),
  ('Tirai Ngelost', 'Tirai error'),
  ('Selang', 'Angin bocor'),
  ('Nipple', 'Angin bocor'),
  ('Cylinder', 'Angin bocor'),
  ('Conector', 'Angin bocor'),
  ('Regulator', 'Angin bocor'),
  ('Selenoid', 'Angin bocor'),
  ('Mengerjakan Part Pending After Robot', 'Part pending'),
  ('Mengerjakan Part Pending After Leaktest', 'Part pending'),
  ('Mengerjakan Part Pending After Part Bocor', 'Part pending'),
  ('Mengerjakan Part Pending After Autocheck', 'Part pending'),
  ('Mengerjakan Part Pending After Pipa Mentok', 'Part pending'),
  ('Mengerjakan Part Pending After Bracket MEntok', 'Part pending'),
  ('Reset', 'Reset'),
  ('Materila Dakon', 'Material'),
  ('Material Scratch', 'Material'),
  ('Material Tidak Ada Ulir', 'Material'),
  ('Material Hole Miring', 'Material'),
  ('Material Burry', 'Material'),
  ('Material Undefill', 'Material'),
  ('Material Shiwa', 'Material'),
  ('Material Crack', 'Material'),
  ('Material GAP', 'Material'),
  ('Material habis', 'Supplay Telat'),
  ('Material Telat', 'Supplay Telat'),
  ('Material tertukar', 'Supplay Telat'),
  ('Material Salah', 'Supplay Telat'),
  ('Material NG', 'Supplay Telat'),
  ('Material berminyak', 'Supplay Telat'),
  ('Material karat', 'Supplay Telat'),
  ('Akurasi NG', 'Akurasi part'),
  ('Single Part Scratch', 'Akurasi part'),
  ('Single Part Dakon', 'Akurasi part'),
  ('Single Part Gap', 'Akurasi part'),
  ('Single Part Banyak Oli', 'Akurasi part'),
  ('Trial Part', 'Akurasi part')
) as t(value, kategori)
on conflict (mesin, problem_kategori, value) do nothing;

-- 3) Area (22 area x 6 line = 132 baris)
insert into public.downtime_areas (mesin, value)
select m.mesin, t.value
from (values
  ('E-02'::machine_type), ('E-03'::machine_type), ('E-04'::machine_type), ('E-05'::machine_type), ('E-06'::machine_type), ('E-07'::machine_type)
) as m(mesin)
cross join (values
  ('ROBOT 1'),
  ('ROBOT 2'),
  ('ROBOT 3'),
  ('ROBOT 4'),
  ('ROBOT 5'),
  ('JIG 1'),
  ('JIG 2'),
  ('JIG 3'),
  ('JIG 4'),
  ('JIG 5'),
  ('JIG 6'),
  ('JIG 7'),
  ('JIG 8'),
  ('MC. SPINNING'),
  ('MC. TIG WELDING'),
  ('MC. TUB CUTTING'),
  ('MC. U & O BENDING'),
  ('PHOTO CAMERA'),
  ('MC. INSERT'),
  ('MC. HAMMERING'),
  ('MC. AUTOCHECK'),
  ('MC. LEAKTEST')
) as t(value)
on conflict (mesin, value) do nothing;

-- =========================================================
-- SELESAI. Cek Table Editor:
--   downtime_problems -> 324 baris
--   downtime_causes    -> 1278 baris
--   downtime_areas     -> 132 baris
-- =========================================================
